const categoryEmojiMap: Record<string, string> = {
  greetings: '👋',
  food: '🍽️',
  drinks: '🥤',
  family: '👨‍👩‍👧',
  numbers: '🔢',
  colors: '🎨',
  animals: '🐾',
  weather: '🌤️',
  travel: '✈️',
  shopping: '🛍️',
  time: '⏰',
  body: '🧍',
  clothing: '👕',
  home: '🏠',
  work: '💼',
  school: '📚',
  health: '🏥',
  sports: '⚽',
  nature: '🌿',
  city: '🏙️',
  transport: '🚌',
  directions: '🧭',
  verbs: '🏃',
  adjectives: '✨',
  pronouns: '👤',
  questions: '❓',
  emotions: '😊',
  restaurant: '🍴',
  hotel: '🏨',
  daily: '📅',
  people: '👥',
  places: '📍',
  activities: '🎯',
  pharmacy: '💊',
  market: '🛒',
  cafe: '☕',
  apartment: '🏢',
  music: '🎵',
};

export function getCategoryEmoji(category: string): string {
  return categoryEmojiMap[category.toLowerCase()] || '📝';
}
